api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
  format: json
  filePath: /var/log/traefik/traefik.json

accessLog:
  format: json
  filePath: /var/log/traefik/access.json

middlewares:
  retry:
    retry:
      attempts: 3
      initialInterval: "500ms"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: financial_manager

entryPoints:
  web:
    address: ":80"


